# Generated by Django 6.0.5 on 2026-05-26 03:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('especialidad', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mecánico',
                'verbose_name_plural': 'Mecánicos',
                'db_table': 'mecanicos',
            },
        ),
        migrations.CreateModel(
            name='ModeloTractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(default='Case', max_length=100)),
            ],
            options={
                'verbose_name': 'Modelo de Tractor',
                'verbose_name_plural': 'Modelos de Tractores',
                'db_table': 'modelos_tractor',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('filtro_combustible', 'Filtro de Combustible'), ('filtro_aceite', 'Filtro de Aceite'), ('filtro_aire', 'Filtro de Aire'), ('lubricante_motor', 'Lubricante de Motor'), ('lubricante_transmision', 'Lubricante de Transmisión'), ('lubricante_hidraulico', 'Lubricante Hidráulico'), ('otro', 'Otro')], max_length=50)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'repuestos',
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractores', to='infrastructure.modelotractor')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractores', to='infrastructure.cliente')),
            ],
            options={
                'verbose_name': 'Tractor',
                'verbose_name_plural': 'Tractores',
                'db_table': 'tractores',
            },
        ),
        migrations.CreateModel(
            name='OrdenMantencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_mantencion', models.CharField(choices=[('mant_50h', '50 Horas'), ('mant_300h', '300 Horas'), ('mant_600h', '600 Horas'), ('mant_1200h', '1200 Horas'), ('reparacion_general', 'Reparación General')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='infrastructure.cliente')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='infrastructure.mecanico')),
                ('repuestos', models.ManyToManyField(related_name='ordenes', to='infrastructure.repuesto')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='infrastructure.tractor')),
            ],
            options={
                'verbose_name': 'Orden de Mantención',
                'verbose_name_plural': 'Órdenes de Mantención',
                'db_table': 'ordenes_mantencion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoRepuestos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_mantencion', models.CharField(choices=[('mant_50h', '50 Horas'), ('mant_300h', '300 Horas'), ('mant_600h', '600 Horas'), ('mant_1200h', '1200 Horas'), ('reparacion_general', 'Reparación General')], max_length=30)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='infrastructure.modelotractor')),
                ('repuestos', models.ManyToManyField(related_name='catalogos', to='infrastructure.repuesto')),
            ],
            options={
                'verbose_name': 'Catálogo de Repuestos',
                'verbose_name_plural': 'Catálogos de Repuestos',
                'db_table': 'catalogo_repuestos',
                'unique_together': {('modelo', 'tipo_mantencion')},
            },
        ),
    ]
