# Generated by Django 6.0.5 on 2026-06-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantencion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
