# Generated by Django 6.0.5 on 2026-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_ordenmantencion_fecha_programada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogorepuestos',
            name='tipo_mantencion',
            field=models.CharField(choices=[('mant_50h', '50 Horas'), ('mant_300h', '300 Horas'), ('mant_600h', '600 Horas'), ('mant_900h', '900 Horas'), ('mant_1200h', '1200 Horas'), ('reparacion_general', 'Reparación General')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ordenmantencion',
            name='tipo_mantencion',
            field=models.CharField(choices=[('mant_50h', '50 Horas'), ('mant_300h', '300 Horas'), ('mant_600h', '600 Horas'), ('mant_900h', '900 Horas'), ('mant_1200h', '1200 Horas'), ('reparacion_general', 'Reparación General')], max_length=30),
        ),
    ]
