# Generated by Django 6.0.5 on 2026-06-13 03:25

import django.db.models.deletion
import infrastructure.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_catalogorepuestos_tipo_mantencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantencion',
            name='nota_cliente',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ImagenOrden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=infrastructure.models.imagen_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='infrastructure.ordenmantencion')),
            ],
            options={
                'verbose_name': 'Imagen de Orden',
                'verbose_name_plural': 'Imágenes de Órdenes',
                'db_table': 'imagenes_orden',
            },
        ),
        migrations.CreateModel(
            name='NotaInterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.mecanico')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_internas', to='infrastructure.ordenmantencion')),
            ],
            options={
                'verbose_name': 'Nota Interna',
                'verbose_name_plural': 'Notas Internas',
                'db_table': 'notas_internas',
                'ordering': ['created_at'],
            },
        ),
    ]
