# Generated by Django 4.2.30 on 2026-07-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_alter_tractor_modelo_and_migrate_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelotractor',
            name='tipo',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('implemento', 'Implemento')], default='tractor', max_length=20),
        ),
    ]
