# Generated by Django 4.2.30 on 2026-07-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_modelotractor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantencion',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='infrastructure.modelotractor'),
        ),
        migrations.AddField(
            model_name='ordenmantencion',
            name='numero_serie_cliente',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordenmantencion',
            name='tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='infrastructure.tractor'),
        ),
    ]
