# Generated by Django 4.2.30 on 2026-07-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_agregar_modelo_y_serie_a_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
