# Generated by Django 4.2.30 on 2026-07-24 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_agregar_telefono_mecanico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horas', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mantención',
                'verbose_name_plural': 'Tipos de Mantención',
                'db_table': 'tipos_mantencion',
                'ordering': ['horas'],
            },
        ),
    ]
